runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: podcasts.app
# [END handlers]

# [START libraries]
libraries:
- name: jinja2
  version: latest
- name: ssl
  version: latest